version: "3.8"
services:
  coderunner:
    image: coc0a25/code-runner:0.3
    container_name: coderunner-dev
    restart: always
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    volumes:
      - ./log/compile:/log/compile
      - ./log/run:/log/run
      - ./log/server:/log/server
      - ./log/system:/log/system
    ports:
    - "0.0.0.0:45000:3000"
